apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse
  namespace: pulse
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: pulse
          imagePullPolicy: IfNotPresent
          env:
            - name: PULSE_REDIS_URL_FILE
              $patch: delete
            - name: PULSE_REDIS_URL
              value: redis://redis:6379
