apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulse-prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml

images:
  - name: pulse
    newName: ghcr.io/your-org/pulse
    newTag: "1.0.0"
