apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse
  namespace: pulse
  labels:
    app: pulse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulse
  template:
    metadata:
      labels:
        app: pulse
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      terminationGracePeriodSeconds: 15
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pulse
          image: pulse:local
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          ports:
            - containerPort: 9090
              name: metrics
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: pulse-config
          env:
            - name: PULSE_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "100m"
              memory: "192Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: tmp
          emptyDir: {}
