apiVersion: v1
kind: ConfigMap
metadata:
  name: pulse-config
  namespace: pulse
data:
  RUST_LOG: "info"
  PULSE_ENDPOINT: "http://account.account.svc.cluster.local:8080"
  PULSE_TARGET_ALLOWLIST: "account.account.svc.cluster.local"
  PULSE_SCENARIOS_FILE: "/app/scenarios.staging.yaml"
  PULSE_KAFKA_BROKERS: "replace-with-managed-staging-kafka:9092"
  PULSE_KAFKA_TOPIC_MANAGEMENT_ENABLED: "false"
  PULSE_KAFKA_TOPIC_REPLICATION_FACTOR: "3"
  PULSE_KAFKA_PRODUCER_QUEUE_MESSAGES: "2048"
  PULSE_KAFKA_CONSUMER_QUEUE_KBYTES: "8192"
